// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


#[derive(Queryable, Debug)]
pub struct UserData {
    pub id: i32,
    pub user_id: i32,
    pub name: String,
    pub fetlife_name: String,
    pub experience_text: String,
    pub found_us_text: String,
    pub goal_text: String,
    pub role_factor: f64,
    pub active_factor: f64,
    pub passive_factor: f64,
    pub open: bool,
    pub show_name: bool,
    pub show_role: bool,
    pub show_experience: bool,
    pub show_open: bool,
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: i32,
    pub email: String,
    pub pw_hash: String,
    pub salt: String,
}

